#-----------------------------------------------------------------------------------------------------------------------
#Language Config - Configurações relacionadas ao sistema de Linguagens

#-----------------------------------------------------------------------------------------------------------------------